# Useful Information

- I didn't use any venvs for this
- I've added an extra test case for case 3 within `test.spec.ts` - one of the test will fail if ran with `npm run test` because of a duplicate entry with the previous tests.
    - Restarting the server and running test3 will fix this issue.
